management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 10000
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: neo_route
#          uri: http://localhost:9000
#          predicates:
#            - Path=/**
logging:
  level:
    org.springframework.cloud.gateway: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true